### ISSUE TITLE
Add centerpiece - BB_Table

### ISSUE THREAD

**Issue by Advaith-RN** [RazerAds/Blender_Blunders#2]
You can spice up the tabletop by adding some coffee for the artist (in a mug preferably).

**Comment by Anjana-Rose** [comment]
Can I work on this?
PES2202200354

**Comment by snaupdog** [comment]
Could i have this issued to me
NIHAL SATISH
PES2202200828

**Comment by Advaith-RN** [comment]
> Can I work on this? PES2202200354

Assigned

**Comment by ankithlemuel** [comment]
Can in work on this?
PES2UG21EC024

**Comment by Keshav1105** [comment]
Can i get this

**Comment by Tree1527** [comment]
Could I have this issue assigned to me
Aditya Rajendra Shinde
PES2202200479

**Comment by snaupdog** [comment]
Yo can you assign this to me pls
PES2202200828
Nihal satish

**Comment by snaupdog** [comment]
Yo can you assign this to me pls
PES2202200828
Nihal satish

**Comment by Tree1527** [comment]
Could I have this issue assigned to me
Aditya Rajendra Shinde
PES2202200479
