### ISSUE TITLE
Reposition Katana - BB_Katana

### ISSUE THREAD

**Issue by Advaith-RN** [RazerAds/Blender_Blunders#3]
The katana has fallen from its stand. Add it back to it correct position.

**Comment by Tree1527** [comment]
Could I have this issue assigned to me
Aditya Rajendra Shinde
PES2202200479

**Comment by snaupdog** [comment]
Could i have this issued to me
NIHAL SATISH
PES2202200828

**Comment by BalajiRock** [comment]
can I work on this @RazerAds
Balaji M (PES2UG21CS117)

**Comment by Anjana-Rose** [comment]
Can I work on this?
PES2202200354

**Comment by BalajiRock** [comment]
> can I work on this @RazerAds Balaji M (PES2UG21CS117)

@RazerAds
