### ISSUE TITLE
Fix the camera - BB_Dinner

### ISSUE THREAD

**Issue by Advaith-RN** [RazerAds/Blender_Blunders#4]
Rotate and position the camera back so that it focuses onto the table.

**Comment by Tree1527** [comment]
Could I have this issue assigned to me
Aditya Rajendra Shinde
PES2202200479

**Comment by snaupdog** [comment]
Could i have this issued to me
NIHAL SATISH
PES2202200828

**Comment by cubed-guy** [comment]
Can I get Assigned to this?
@RazerAds

**Comment by cubed-guy** [comment]
Can I get assigned to this issue?
PES2UG21CS477 Sanket Padhi

**Comment by snaupdog** [comment]
can i get assigned to this issue
PES2202200828
nihal satish
