### ISSUE TITLE
Add glasses - BB_Dinner

### ISSUE THREAD

**Issue by Advaith-RN** [RazerAds/Blender_Blunders#5]
The table includes everything except glasses to drink out of. Add some!

**Comment by snaupdog** [comment]
Hey can i get this issued to me

**Comment by Anjana-Rose** [comment]
can I work on this?
PES2202200354

**Comment by snaupdog** [comment]
Could i have this issued to me
NIHAL SATISH
PES2202200828

**Comment by cubed-guy** [comment]
Can I get assigned to this?
@RazerAds

**Comment by Vaarun-Kamath** [comment]
hey can I get this pls :)

**Comment by ankithlemuel** [comment]
can i work on this?
PES2UG21EC024

**Comment by snaupdog** [comment]
> 

almost done

**Comment by Keshav1105** [comment]
Can i get this

**Comment by Tree1527** [comment]
Could I have this issue assigned to me
Aditya Rajendra Shinde
PES2202200479

**Comment by Tree1527** [comment]
Could I have this issue assigned to me
Aditya Rajendra Shinde
PES2202200479

**Comment by Anjana-Rose** [comment]
Can I work on this?
PES2202200354

**Comment by Keshav1105** [comment]
Can i work on this

**Comment by NandanHemanth** [comment]
Can you please assign this to me
