### ISSUE TITLE
Change the lighting - BB_Katana

### ISSUE THREAD

**Issue by Advaith-RN** [RazerAds/Blender_Blunders#6]
Currently, the katana resides in scene lit up by the harsh noon sun. Change the lighting setup to a moonlit night, to give the scene a touch of serenity.

**Comment by Tree1527** [comment]
Could I have this issue assigned to me
Aditya Rajendra Shinde
PES2202200479

**Comment by Advaith-RN** [comment]
> Could I have this issue assigned to me Aditya Rajendra Shinde PES2202200479

Assigned

**Comment by Vaarun-Kamath** [comment]
hey can I get this pls :) PES2UG21CS594

**Comment by ankithlemuel** [comment]
can i work on this?
PES2UG21EC024

**Comment by snaupdog** [comment]
Yo can you assign this to me pls
PES2202200828
Nihal satish
